name: ServiceLearningWebsite
version: 0.0.1
author: Dart Team <misc@dartlang.org>
description: A simple example of a full polymer app with multiple pages.
homepage: https://github.com/dart-lang/polymer-spa-example
environment:
  sdk: any
dependencies:
  core_elements: any
  paper_elements: any
  polymer: any
  route_hierarchical: any
transformers:
- polymer:
    entry_points: web/index.html
- $dart2js:
    $include: '**/*.polymer.bootstrap.dart'
